#!/usr/bin/env bash
IFS=$'\t\n';
set -euo pipefail;


ddbDir="$PWD";
ddbFile="";
while [ ! -f "$ddbDir"/*.ddb ]
do
	ddbDir=${ddbDir%/*};
done;
for ddbFile in "$ddbDir"/*.ddb
do
	[ -f "$ddbFile" ] && break;
done;


datafile="financial-data.txt";
duckdb "$ddbFile" <property-tax-data.sql |
sed 's/NULL//g;' > "$datafile";


for file in [a-zA-Z]*.gpi
do
	base=${file/.gpi/};
	echo "generating $base from $file";
	minCol=$(head -1 "$file");
	range=$(sed -n '2{s/  *#.*//;p;q;}' "$file");
	sed -n "/^$range/,\$p" "$datafile" > "${base}.txt";
	(
		sed "
			s/FILENAME/$base/g;
			s/MINCOL/$minCol/;
		" _header.gpi;
		sed -n '3,$p' "$file";
	) | tee /tmp/"$file" | gnuplot;
	rm "${base}.txt";
done;
