#!/usr/bin/env bash
IFS=$'\t\n';
set -euo pipefail;


ddbDir="$PWD";
ddbFile="";
while [ ! -f "$ddbDir"/*.ddb ]
do
	ddbDir=${ddbDir%/*};
done;
for ddbFile in "$ddbDir"/*.ddb
do
	[ -f "$ddbFile" ] && break;
done;

file="budget.tsv";
if [ ! -f "$file" ]
then
	cat <<EOF
File "$file" doesn't exist.
Compile data from the budget documents from 2008 onward, available at
  - https://fitchburgwi.gov/2234/Past-Budgets
  - https://fitchburgwi.gov/1998/Financial-Records-Reports

Make data columns as follows:
     0	 A	Year
     1	 B	Levy Revenue Page
     2	 C	General
     3	 D	FACTv
     4	 E	Transit
     5	 F	Library
     6	 G	Debt
     7	 H	Capital
     8	 I	TID Alloc
     9	 J	City Total
    10	 K	MMSD
    11	 L	Oregon
    12	 M	Verona
    13	 N	MATC
    14	 O	Dane
    15	 P	State Forest
    16	 Q	Grand Total
    17	 R	InterGov Pg
    18	 S	InterGov
    19	 T	Assessed Value Page
    20	 U	AssessedValue
    21	 V	Equalized Value
    22	 W	Ratio
    23	 X	SFH Data Page
    24	 Y	SFH Assessed
    25	 Z	SFH Tax
    26	AA	MF Assessed
    27	AB	MF Tax

Copy from the spreadsheet including 1 header line into a text file with tab delimiter and save.
EOF
fi;

code="$(readlink -f -- "$0";)";
code=${code%/*};
code=${code##*-};

awk '
# skip header and rely on column order instead of names
FNR == 1 {next;}

/[,$]/ {
	gsub(/[,$]/,"");
	gsub(/#DIV\/0!/,"");
	print;
}' "$file" |
duckdb "$ddbFile" "
delete from MuniBudget where MuniCode = $code;
insert into MuniBudget
	select
		 MuniCode          : $code
		,Year              : column00
		,LevyGeneral       : column02
		,LevyTransit       : column04
		,LevyLibrary       : column05
		,LevyDebt          : column06
		,LevyCapital       : column07
		,LevyTID           : column08
		,LevyCityOther     : column03    -- FACTv

		,InterGovRevenue   : column18

		,LevySchool1       : column10
		,LevySchool2       : column11
		,LevySchool3       : column12
		,LevyTechCollege   : column13
		,LevyCounty        : column14
		,LevyOverlyingOther: column15    -- State Forest


		,AssessedValue     : column20
		,EqualizedValue    : column21
		,MedianSFAssessed  : column24
		,MedianMFAssessed  : column26
		,MedianSFTax       : column25
		,MedianMFTax       : column27
	from read_csv('/dev/stdin')
";
